In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("dom_buh.csv")

In [ ]:
df.describe()

              Сумма
count     32.000000
mean    1672.812500
std     3656.756772
min       39.000000
25%      195.500000
50%      475.000000
75%      877.500000
max    17948.000000

In [ ]:
df_small = df[['Категория','Сумма']]

In [ ]:
df_small.groupby('Категория').sum()

             Сумма
Категория
Еда         2289.0
Медицина    4123.0
Одежда      8714.0
Техника    33944.0
Услуги      4460.0